name: deploy-book

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: Check _build/html directory
      run: ls -lR _build/html || echo "Directory not found"

    - name: Ensure _build/html exists
      run: mkdir -p _build/html

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: _build/html

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
      with:
        artifact_name: github-pages
